FROM node:12-alpine

WORKDIR /usr/src/app

ENV PATH /usr/src/app:$PATH
ENV DIR ../build

COPY ./package*.json /usr/src/app/
COPY ./src/ /usr/src/app/src/
COPY ./public/ /usr/src/app/public/

RUN ["npm", "install"]
RUN ["npm", "run-script", "build"]

CMD ["node", "src/server.js"]